from .west import Ka
from .west import Ta
from .west import Ha
from .west import Ra
from .west import Wa
from .west import Ki
from .west import Chi
from .west import Hi
from .west import Ri

from .east import Sa
from .east import Na
from .east import Ma
from .east import A
from .east import Ya
from .east import Shi
from .east import Ni
from .east import Mi
from .east import I
